# -*- coding: utf-8 -*-
# **************************************************************************
# *
# * Authors:     Blanca Pueche (blanca.pueche@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
"""
Protocol to strip water from an OpenMMSystem produced by ProtOpenMMSystemSimulation.
"""
import os
import shutil

from pwem.convert.atom_struct import pdbToCif
from pyworkflow.protocol import params
from pyworkflow.utils import Message
import subprocess
from pwem.protocols import EMProtocol

from .. import Plugin
from ..constants import OPENMM_DIC
from ..objects import OpenMMSystem

class ProtStripWater(EMProtocol):
    """
    This protocol removes water molecules from an OpenMMSystem produced by a simulation.

    AI Generated:

        ProtStripWater - User Manual

        Overview
        --------
        The ProtStripWater protocol processes OpenMMSystem objects generated by
        ProtOpenMMSystemSimulation to remove explicit water molecules from the system.
        This can reduce file size, simplify analysis, and prepare systems for
        further simulations or post-processing steps. Users can optionally preserve
        ions while stripping water to maintain system neutrality or ionic strength.

        Inputs and General Workflow
        ---------------------------
        The protocol requires an OpenMMSystem as input, which contains topology, coordinates,
        and trajectory files (PDB, DCD, and CIF). Users can configure whether ions should
        be kept during the water-stripping process.

        The workflow is divided into two main stages:

        1. **Water Stripping**:
            - Generates a parameters file specifying input PDB/DCD files and output naming.
            - Calls the `stripWater.py` script to remove water molecules from the system.
            - Optionally preserves ions if `keepIons` is set to True.

        2. **Output Creation**:
            - Generates cleaned PDB, DCD, and CIF files.
            - Copies OpenMMDL analysis directories if present in the input system.
            - Produces a new OpenMMSystem object containing the stripped structure and updated
              trajectory information.

        Options
        -------
        - `keepIons`: Boolean parameter; if True, ions are preserved in the system.
        - Input system: OpenMMSystem object generated by a previous MD simulation protocol.

        Outputs and Interpretation
        --------------------------
        After execution, the protocol generates:

        - Stripped PDB file containing only non-water residues (optionally ions included)
        - Updated DCD trajectory file corresponding to the stripped system
        - CIF file converted from the cleaned PDB for compatibility with other tools
        - OpenMMDL analysis directory copied from the input system if available
        - OpenMMSystem object representing the stripped system, ready for further analysis

        Practical Recommendations
        -------------------------
        - Use this protocol after production MD to reduce system size before analysis.
        - Keep ions if studying electrostatic interactions or ionic effects.
        - Validate trajectory continuity after water removal, especially if ions were removed.
        - Use the generated OpenMMSystem for downstream protocols such as docking, binding
          analysis, or visualization.

        Final Perspective
        -----------------
        ProtStripWater provides an automated, reproducible, and flexible method for
        removing water molecules from OpenMM simulation systems. It facilitates
        streamlined analyses, reduces computational overhead for post-processing,
        and ensures compatibility with downstream protocols and visualization tools.
    """

    _label = 'strip water from OpenMM system'

    def _defineParams(self, form):
        form.addSection(label=Message.LABEL_INPUT)
        g = form.addGroup('Input')
        g.addParam('inputSystem', params.PointerParam, label='Input system: ', pointerClass='OpenMMSystem',
                   help='OpenMMSystem produced by the simulation protocol.', allowsNull=False, important=True)

        g = form.addGroup('Options')
        g.addParam('keepIons', params.BooleanParam, default=True,
                   label='Keep ions: ', help='If True, ions are preserved; otherwise they are removed with water.')

    def _insertAllSteps(self):
        self._insertFunctionStep("stripStep")
        self._insertFunctionStep("createOutputStep")

    def stripStep(self):
        pdbFile = self.inputSystem.get().getFileName()
        name = os.path.splitext(os.path.basename(pdbFile))[0]
        systemPath = os.path.dirname(pdbFile)
        dcdIn = os.path.join(systemPath, f"{name}.dcd")

        paramsFile = self._getExtraPath('strip_params.txt')
        outPrefix = self._getPath(f'{name}_clean')
        with open(paramsFile, 'w') as f:
            f.write(f'pdbIn :: {os.path.abspath(pdbFile)}\n')
            f.write(f'dcdIn :: {os.path.abspath(dcdIn)}\n')
            f.write(f'outPrefix :: {os.path.abspath(outPrefix)}\n')
            f.write(f'keepIons :: {self.keepIons.get()}\n')

        Plugin.runScript(self, 'stripWater.py', args=os.path.abspath(paramsFile), env=OPENMM_DIC, cwd=self._getPath())

    def createOutputStep(self):
        pdbFile = self.inputSystem.get().getFileName()
        name = os.path.splitext(os.path.basename(pdbFile))[0]
        suffix = '_clean'
        outPdb = self._getPath(f'{name}{suffix}.pdb')
        outDcd = self._getPath(f'{name}{suffix}.dcd')

        outCif = self._getPath(f'{name}{suffix}.cif')
        pdbToCif(outPdb, outCif)

        mFF, wFF = self.getFFFiles()
        nFrames = self.inputSystem.get().getNFrames()
        nTime = self.inputSystem.get().getNTime()

        outSystem = OpenMMSystem(filename=outPdb, serieFile=outDcd if os.path.exists(outDcd) else '',
                                 cifFile=outCif, ff=mFF, wff=wFF, nFrames=nFrames, nTime=nTime, topoFile=outPdb)

        if os.path.exists(outDcd):
            outSystem.setTrajectoryFile(outDcd)

        inSystem = self.inputSystem.get()
        inAnaDir = inSystem.getOpenmmdlDir() if hasattr(inSystem, 'getOpenmmdlDir') else None

        if inAnaDir and os.path.exists(inAnaDir):
            outAnaDir = self._getExtraPath('OpenMMDL')
            if not os.path.exists(outAnaDir):
                shutil.copytree(inAnaDir, outAnaDir)
            outSystem.setOpenmmdlDir(outAnaDir)

        self._defineOutputs(outputSystem=outSystem)

    def getFFFiles(self):
        system = self.inputSystem.get()
        return system.getForceField(), system.getWaterForceField()