[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Molecular Dynamics", "children": [
	    {"tag": "protocol_group", "text": "System preparation", "openItem": "False", "children": [
	        {"tag": "protocol", "value": "ProtOpenMMSystemPrep",   "text": "default"}
	    ]},
	    {"tag": "protocol_group", "text": "MD simulation", "openItem": "False", "children": [
	        {"tag": "protocol", "value": "ProtOpenMMSystemSimulation",   "text": "default"},
            {"tag": "protocol", "value": "ProtOpenDuckSimulation",   "text": "default"}
	    ]},
	    {"tag": "protocol_group", "text": "Simulation analysis", "openItem": "False", "children": [
            {"tag": "protocol", "value": "ProtStripWater",   "text": "default"}
        ]}
	]}
    ]